name: tictactoe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dart:
  experiments:
    - dot-shorthands

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  rive: ^0.13.20
  go_router: ^17.0.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  font_awesome_flutter: ^10.12.0
  carousel_slider: ^5.1.1
  mocktail: ^1.0.4

dev_dependencies:
  build_runner: ^2.10.3
  riverpod_generator: ^3.0.3
  go_router_builder: ^4.1.1
  flutter_lints: ^6.0.0

  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide/Audiowide-Regular.ttf
